# Chloe Fugle (chloe.m.fugle.23@dartmouth.edu)
# Shoals Marine Laboratory Internship, 7/20/2022
# Get distribution of number of nests per neighborhood and the relationship
# of nest number and productivity of the neighborhood

# replace this with the path to your data on your computer
# note: if you copy-paste the path on a Windows computer, it will have "\" in 
#       the path - please replace all "\" with "/" for R to interpret it correctly
PRODUCTIVITY_DATA = "C:/Users/sapph/Downloads/ROST productivity raw data 2016-2021.xlsx"

# import packages
library(readxl)
library(dplyr)
library(ggplot2)
library(RColorBrewer)

################################################################################
# import data from "ROST productivity raw data 2016-2021.xlsx"
prod_2017 <- read_excel(PRODUCTIVITY_DATA, sheet="Productivity 2017")
prod_2018 <- read_excel(PRODUCTIVITY_DATA, sheet="Productivity 2018")
prod_2019 <- read_excel(PRODUCTIVITY_DATA, sheet="Productivity 2019")
prod_2020 <- read_excel(PRODUCTIVITY_DATA, sheet="Productivity 2020")
prod_2021 <- read_excel(PRODUCTIVITY_DATA, sheet="Productivity 2021")

# extract neighborhood and nest data from raw data
# note: code is specific to each year because the data is recorded differently
nests_2017 = prod_2017[c("Plot/Area...1", "Nest Number")]
nests_2017['Year'] = 2017
colnames(nests_2017) = c("Neighborhood", "Nest_Number", "Year")

nests_2018 = prod_2018[c("Island/area", "Nest Number")]
nests_2018['Year'] = 2018
colnames(nests_2018) = c("Neighborhood", "Nest_Number", "Year")

nests_2019 = prod_2019[c("Plot/Area", "Nest Number")]
nests_2019['Year'] = 2019
colnames(nests_2019) = c("Neighborhood", "Nest_Number", "Year")

nests_2020 = prod_2020[c("Plot/Area", "Nest Number")]
nests_2020['Year'] = 2020
colnames(nests_2020) = c("Neighborhood", "Nest_Number", "Year")

nests_2021 = prod_2021[c("Plot/Area", "Nest Number")]
nests_2021['Year'] = 2021
colnames(nests_2021) = c("Neighborhood", "Nest_Number", "Year")

########################################################################
# combine year dataframes into one and process the data

nests_all <- rbind(nests_2017, nests_2018, nests_2019, nests_2020, nests_2021)

# function to extract numbers from string
# input: x - string
# output: x_numbers - list of the single-digit integers contained in the string
extract_nums = function(x, output){
  x_numbers <- regmatches(x, gregexpr("[[:digit:]]+", x))
  return(x_numbers)
}

# function to collapse list of integers into string
# input: x - list of numbers
# output: x_string - string of numbers
collapse_nums = function(x, output){
  x_string = paste(unlist(x),collapse="")
  return(x_string)
}

# extract neighborhood number from string
neigh_num <- apply(nests_all[,1], 1, extract_nums)
neigh_num_str <- lapply(neigh_num, collapse_nums)
nests_all$Neighborhood_Number <- neigh_num_str

# remove rows with uncertain neighborhood (have multiple or no neighborhoods listed)
nests_all_seg <- subset(nests_all, nchar(Neighborhood_Number) == 1)
nests_all_seg = nests_all_seg[c("Nest_Number", "Year", "Neighborhood_Number")]
nests_all_seg <- nests_all_seg %>% relocate("Neighborhood_Number")
nests_all_seg <- nests_all_seg %>% relocate("Year")
nests_all_seg = unique(nests_all_seg)

################################################################################
# get number of nests in each neighborhood each year
year = vector(mode = "list", length = 0)
neighborhood = vector(mode = "list", length = 0)
no_nests = vector(mode = "list", length = 0)

for(i in 2017:2021){
  for(j in 1:9){
    temp_data = nests_all_seg[nests_all_seg$Year == i & 
                                nests_all_seg$Neighborhood_Number == j,]
    year = c(year, i)
    neighborhood = c(neighborhood, j)
    no_nests = c(no_nests, nrow(temp_data))
  }
}

nests_number = as.data.frame(cbind(year, neighborhood, no_nests))
colnames(nests_number) = c("Year", "Neighborhood", "Number_of_Nests")
nests_number <- as.data.frame(lapply(nests_number, unlist))

################################################################################
# examine effects of number of nests in each neighborhood on productivity, resights

# perform one-way ANOVA modeling tern age as a function of neighborhood
anova = aov(Number_of_Nests ~ Neighborhood, data = nests_number)
plot(anova)   # check for homoscedasticity
tukey = TukeyHSD(anova)   # perform Tukey HSD Pst-Hoc test

# plot number of nests in each neighborhood each year
nests_number$Number_of_Nests = as.numeric(nests_number$Number_of_Nests)
nests_number$Neighborhood = as.factor(nests_number$Neighborhood)
nests_number %>%                                           
  ggplot(aes(x=Neighborhood,y=Number_of_Nests)) +            
  geom_boxplot() +                                     
  labs(x="Neigborhood",y="Number of Nests")

# get percent fledged by year by neighborhood generated by productivity.R script
prod_by_neighyear = readRDS(file="Mean_Productivity_by_Year_by_Neighborhood")
nests_number$Percent_Fledged = prod_by_neighyear

# plot percent fledged against number of nests in a neighborhood
nests_number$Percent_Fledged = as.numeric(nests_number$Percent_Fledged)
nests_number %>%                                           
  ggplot(aes(x=Number_of_Nests,y=Percent_Fledged)) +            
  geom_point() +                                     
  labs(x="Number of Nests in Neigborhood",y="% Fledged")


################################################################################
# plot number of resights in each neighborhood by number of nests

# get number of resights in each neighborhood each year
resights_by_neighyear = readRDS(file="Resights by Neighborhood and Year")

r_year = vector(mode = "list", length = 0)
r_neighborhood = vector(mode = "list", length = 0)
no_resights = vector(mode = "list", length = 0)

for(i in 2017:2021){
  for(j in 1:9){
    temp_resights_data = resights_by_neighyear[resights_by_neighyear$Year == i & 
                                        resights_by_neighyear$Neighborhood_Number == j,]
    r_year = c(r_year, i)
    r_neighborhood = c(r_neighborhood, j)
    no_resights = c(no_resights, nrow(temp_resights_data))
  }
}

resights_number = as.data.frame(cbind(r_year, r_neighborhood, no_resights))
colnames(resights_number) = c("Year", "Neighborhood", "Number_of_Resights")
resights_number <- as.data.frame(lapply(resights_number, unlist))

# add number of resights to nest/productivity data frame
nests_number$Number_of_Resights = resights_number$Number_of_Resights

# plot number of resights by number of nests
nests_number$Number_of_Resights = as.numeric(nests_number$Number_of_Resights)
nests_number %>%                                           
  ggplot(aes(x=Number_of_Nests,y=Number_of_Resights)) +            
  geom_point() +   
  geom_abline(intercept=0,slope=1, color="red4") +
  labs(x="Number of Nests in Neigborhood",y="Number of Resights")

# plot resights in each neighborhood/number of nests in each neighborhood x2
# (number of adult birds in each neighborhood)
resights_nests = nests_number[nests_number$Number_of_Nests != 0,]
resights_nests$Percent_Resight = resights_nests$Number_of_Resights/ 
                                    (resights_nests$Number_of_Nests * 2)

resights_nests$Percent_Resight = as.numeric(resights_nests$Percent_Resight)
resights_nests %>%                                           
  ggplot(aes(x=Neighborhood,y=Percent_Resight)) +            
  geom_boxplot(fill='slategray1', color="black", alpha = 0.8) + 
  labs(x="Neigborhood",y="Number of Resights /\n Number of Birds")
